#!/bin/csh -f

set tempfile = `sed -n 1p title`
set filename  = $tempfile
set psformat  = $filename".ps"
set epsformat = $filename".eps"

gnuplot -persist << EOF

set title "$filename"
set size 0.7,1.0
set xr[-12.0:6.0]
set xl "{/=30 Energy  / eV}"
set yr[0.0:*]
set yl "{/=30 Density of States / eV}"

set yzeroaxis lt 2 lw 2 lc rgb "black"

# linetype=lt, linecolor=lc, linewidth=lw, pointtype=pt, pointsize=ps
# with=w, line=l, color setting=lc rgb "",
set key box center top

# dos_updn
#plot "dos_updn" using 1:2 w l lt 1 lw 2 lc rgb "black" title "{/=30 up spin}", "dos_updn" using 1:3 w l lt 1 lw 2 lc rgb "black" title "{/=30 down spin}"

# tdos
plot "tdos" using 1:2 w l lt 1 lw 2 lc rgb "black" title "{/=30 total}"

unset key
#set key left top

set size 1.0,1.0
set terminal postscript color enhanced "Arial" 30
set out "$psformat"
replot

#set size 1.5,2.1
#set terminal postscript eps color enhanced "Arial" 30
#set out "$epsformat"
#replot

set terminal x11

EOF
